export const ROLES = {
  OWNER: "owner",
  ADMIN: "admin",
  STAFF: "staff",
  VIEWER: "viewer",
};

export const ROLE_GROUPS = {
  CONTACT_MUTATE: [ROLES.OWNER, ROLES.ADMIN, ROLES.STAFF],
  CONTACT_VIEW: [ROLES.OWNER, ROLES.ADMIN, ROLES.STAFF, ROLES.VIEWER],
  BUSINESS_ADMIN: [ROLES.OWNER, ROLES.ADMIN],
  MEMBER_MANAGEMENT: [ROLES.OWNER, ROLES.ADMIN],
  INVITATION_MANAGEMENT: [ROLES.OWNER, ROLES.ADMIN],
  LEAD_MUTATE: [ROLES.OWNER, ROLES.ADMIN, ROLES.STAFF],
  LEAD_DELETE: [ROLES.OWNER, ROLES.ADMIN],
};
